version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # this points to location of requiremenmts.txt
    schedule:
      interval: "daily"
      time: "18:00"
    commit-message:
      prefix: "fix"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
